@startuml

' 図書館貸出システム
class 登場人物 {
    図書館の蔵書
    利用者
    貸出情報
}

class 書籍情報 {
    書籍名
    著者
    貸出中フラグ
}

class 利用者情報 {
    名前
    連絡先
    借りフラグ
    返却期限切れフラグ
}

class 貸出情報 {
    書籍名
    貸出日
    返却期限
    返却日
}

@enduml