@startuml

class 図書館 {

}

class 蔵書管理 {
    登録()
    削除()
    更新()
    参照()
}

class 書籍 {
    書籍名
    著者名
}

class 貸出システム {
}

class 貸出情報 {
    登録()
    削除()
    更新()
    参照()    
}

class 返却情報 {
    登録()
    削除()
    更新()
    参照()
}
class 利用者管理 {
    登録()
    削除()
    更新()
    参照()
}

書籍 o-- 図書館
図書館 o-- 蔵書管理
図書館 o-- 利用者管理
貸出システム o- 貸出情報
貸出システム o- 返却情報

貸出システム ..> 蔵書管理:蔵書参照
貸出システム ..> 利用者管理:利用者参照
@enduml