# Generated by Django 5.0.1 on 2024-02-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('auther', models.CharField(blank=True, default='', max_length=100)),
                ('aaa', models.CharField(blank=True, default='', max_length=100)),
                ('bbb', models.IntegerField(blank=True, default='')),
                ('ccc', models.FloatField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
