# Generated by Django 5.0.1 on 2024-01-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_lent',
            field=models.BooleanField(default=False),
        ),
    ]
