# Generated by Django 5.0.1 on 2024-01-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='borrowed_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
